mv delivery/apples fruit
mv delivery/bison_Burgers meat
mv delivery/carrot_cake.txt dessert
mv delivery/fage_yogurt.txt dairy
mv delivery/flourless_cake.txt dessert
mv delivery/garlic.txt veggies
mv delivery/goldfish.txt snax
mv delivery/grapples.txt fruit
mv delivery/hotdogs.txt meat
mv delivery/icecream.txt dessert
mv delivery/lamb_ribs.txt meat
mv delivery/land_o_lakes_butter.txt dairy
mv delivery/lean_cuisine.txt freezer
mv delivery/leeks.txt veggies
