mv delivery/apples fruit
mv delivery/bison_Burgers meat
mv delivery/carrot_cake.txt dessert
mv delivery/fage_yogurt.txt dairy
mv delivery/flourless_cake.txt dessert
mv delivery/garlic.txt veggies
mv delivery/goldfish.txt snax
mv delivery/grapples.txt fruit
mv delivery/hotdogs.txt meat
mv delivery/icecream.txt dessert
mv delivery/lamb_ribs.txt meat
mv delivery/land_o_lakes_butter.txt dairy
mv delivery/lean_cuisine.txt freezer
mv delivery/leeks.txt veggies
mv delivery/milk.txt dairy
mv delivery/mint_milano_cookies.txt dessert
mv delivery/onion.txt veggies
mv delivery/oreos.txt dessert
mv delivery/potatoes.txt veggies
mv delivery/salmon_steak.txt meat
mv delivery/tiramisu_cake.txt dessert
mv delivery/tomatoes.txt veggies
mv delivery/trail_mix.txt snax
mv delivery/turkey_breat.txt meat
mv delivery/velveeta_cheese.txt dairy
mv delivery/watermelon.txt fruit
mv delivery/